### ISSUE TITLE
How to use VoiceStateUpdate/VoiceServerUpdate ?

### ISSUE THREAD

**Issue by fiwippi** [DisgoOrg/disgolink#30]
Hi, I've looked around at this repo and the Lavalink docs and apart from having to join a voice channel and sending the play command to Lavalink, you also have to send VoiceStateUpdate or VoiceServerUpdate op to Lavalink (I'm not sure which one).

Could you please explain/provide an example? 

For context I'm using the non-specific implementation.

Thanks

**Comment by TopiSenpai** [comment]
Which discord library are you using?

**Comment by TopiSenpai** [comment]
When connecting to a voice channel you need to send a voice state update command over the gateway https://discord.com/developers/docs/topics/gateway#update-voice-state

This then fires a voice state update & voice server update

Both of them need to be forwarded to lavalink

This can be done via `lavalink.OnVoiceStateUpdate` and `lavalink.OnVoiceServerUpdate`

**Comment by TopiSenpai** [comment]
I'll update the docs to include that later

**Comment by fiwippi** [comment]
Thanks

**Comment by TopiSenpai** [comment]
I'd be open for a simple wrapper like
https://github.com/DisgoOrg/disgolink/tree/master/dgolink
or
https://github.com/DisgoOrg/disgolink/tree/master/disgolink 
for arikawa

you can pr it or I'll do it how you like

**Comment by fiwippi** [comment]
I'm happy to do it but I'm about to start a new semester so it might take a while... :(

**Comment by TopiSenpai** [comment]
alright dw about it then
