### ISSUE TITLE
No reconnect on: CloseAbnormalClosure

### ISSUE THREAD

**Issue by Steav005** [disgoorg/disgolink#41]
With 4bd1cfd, `CloseAbnormalClosure` was added as an expected Websocket close error.  
https://github.com/disgoorg/disgolink/blob/ae2c5b14b1ac427f7bdfe1ff8ed4ab4be6cc7160/lavalink/node.go#L146

This results in the node not attempting a reconnect.  
Furthermore, no log is printed and the bot stops working until manually calling reconnect or recreating the node.
`CloseAbnormalClosure` should be removed from the list of expected error since an AbnormalClosure is never expected

**Comment by TopiSenpai** [comment]
honestly looking it now `CloseGoingAway` should not be ignored too

**Comment by TopiSenpai** [comment]
alright I reworked the logic a bit
let me know what you think
https://github.com/disgoorg/disgolink/pull/42

**Comment by Steav005** [comment]
I like that one.  
But the new `reconnect` variable feels kinda useless.  
Wouldn't it make more sense like this:

```go
if err != nil {
	n.Close()
	if !errors.Is(err, net.ErrClosed) {
		go n.reconnect(context.TODO())
	}
	break loop
}
```

**Comment by TopiSenpai** [comment]
uhm thats a fair point haha

**Comment by Steav005** [comment]
Perfekt, thank you

**Comment by TopiSenpai** [comment]
thx for reporting!
